#!/usr/bin/env python
# @Author: David Haas
# CONST
APP_HOST = 'localhost'
APP_PORT = 8080
MONGO_HOST = 'localhost'
MONGO_PORT = 27017
DB_NAME = 'timeuse'

# Fields could be excluded here in the future if there is no reason to work with them
FIELDS = {
    '_id': True,
    'countrya': True,
    'survey': True,
    'swave': True,
    'msamp': True,
    'hhldid': True,
    'persid': True,
    'id': True,
    'parntid1': True,
    'parntid2': True,
    'partid': True,
    'day': True,
    'month': True,
    'year': True,
    'diary': True,
    'badcase': True,
    'hhtype': True,
    'hhldsize': True,
    'nchild': True,
    'agekidx': True,
    'agekid2': True,
    'incorig': True,
    'income': True,
    'ownhome': True,
    'urban': True,
    'cohab': True,
    'computer': True,
    'vehicle': True,
    'sex': True,
    'age': True,
    'famstat': True,
    'singpar': True,
    'civstat': True,
    'citizen': True,
    'empstat': True,
    'emp': True,
    'unemp': True,
    'student': True,
    'retired': True,
    'empsp': True,
    'workhrs': True,
    'occup': True,
    'sector': True,
    'educa': True,
    'rushed': True,
    'health': True,
    'carer': True,
    'disab': True,
    'main1': True,
    'main2': True,
    'main3': True,
    'main4': True,
    'main5': True,
    'main6': True,
    'main7': True,
    'main8': True,
    'main9': True,
    'main10': True,
    'main11': True,
    'main12': True,
    'main13': True,
    'main14': True,
    'main15': True,
    'main16': True,
    'main17': True,
    'main18': True,
    'main19': True,
    'main20': True,
    'main21': True,
    'main22': True,
    'main23': True,
    'main24': True,
    'main25': True,
    'main26': True,
    'main27': True,
    'main28': True,
    'main29': True,
    'main30': True,
    'main31': True,
    'main32': True,
    'main33': True,
    'main34': True,
    'main35': True,
    'main36': True,
    'main37': True,
    'main38': True,
    'main39': True,
    'main40': True,
    'main41': True,
    'main42': True,
    'main43': True,
    'main44': True,
    'main45': True,
    'main46': True,
    'main47': True,
    'main48': True,
    'main49': True,
    'main50': True,
    'main51': True,
    'main52': True,
    'main53': True,
    'main54': True,
    'main55': True,
    'main56': True,
    'main57': True,
    'main58': True,
    'main59': True,
    'main60': True,
    'main61': True,
    'main62': True,
    'main63': True,
    'main64': True,
    'main65': True,
    'main66': True,
    'main67': True,
    'main68': True,
    'main69': True,
    'cphome': True,
    'relrefp': True,
    'empinclm': True,
    'edcat': True

}
# These Fields are currently not used in the visualisation
FIELDS_EXCLUDED = {
    'swave': False,
    'msamp': False,
    'hldid': False,
    'persid': False,
    'parntid1': False,
    'parntid2': False,
    'partid': False,
    'month': False,
    'diary': False,
    'incorig': False,
    'cphome': False,
    'relrefp': False,
    'empinclm': False,
    'av1': False,
    'av2': False,
    'av3': False,
    'av4': False,
    'av5': False,
    'av6': False,
    'av7': False,
    'av8': False,
    'av9': False,
    'av10': False,
    'av11': False,
    'av12': False,
    'av13': False,
    'av14': False,
    'av15': False,
    'av16': False,
    'av17': False,
    'av18': False,
    'av19': False,
    'av20': False,
    'av21': False,
    'av22': False,
    'av23': False,
    'av24': False,
    'av25': False,
    'av26': False,
    'av27': False,
    'av28': False,
    'av29': False,
    'av30': False,
    'av31': False,
    'av32': False,
    'av33': False,
    'av34': False,
    'av35': False,
    'av36': False,
    'av37': False,
    'av38': False,
    'av39': False,
    'av40': False,
    'av41': False,
    'av42': False,
    'av43': False,
    'av44': False,
    'av45': False,
    'av46': False,
    'av47': False,
    'sspart': False,
    'ocombtw': False,
    'propbwt': False
}

countrya = {
    1: 'Armenia',
    2: 'Australia',
    3: 'Austria',
    4: 'Belgium',
    5: 'Brazil',
    6: 'Bulgaria',
    7: 'Canada',
    8: 'China',
    9: 'Denmark',
    10: 'Estonia',
    11: 'Finland',
    12: 'France',
    13: 'Germany',
    14: 'Hungary',
    15: 'India',
    16: 'Ireland',
    17: 'Isreal',
    18: 'Italy',
    19: 'Japan',
    20: 'Latvia',
    21: 'Lithuania',
    22: 'Netherlands',
    23: 'New Zealand',
    24: 'Norway',
    25: 'Pakistan',
    26: 'Poland',
    27: 'Portugal',
    28: 'Republic of Korea',
    29: 'Romania',
    30: 'Serbia / Yugoslavia',
    31: 'Slovak Republic/Czechoslovakia',
    32: 'Slovenia/ Yugoslavia',
    33: 'South Africa',
    34: 'Spain',
    35: 'Sweden',
    36: 'Turkey',
    37: 'United Kingdom',
    38: 'USA'
}
# Countries not included
# EXCLUDED = [1,2,4,5,6,7,8,9,10,11,14,15,16,17,19,20,22,23,24,25,26,27,28,29,30,31,32,33, 35,36,38]
# INCLUDED = [3,12,13,18,22,34,37]
INCLUDED = [3, 12, 13, 18, 22, 37, 34]
